HW_10/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('', include('users.urls'))
]

HW_10/hw_project/quotes/urls.py
from django.urls import path

from .import views

app_name = 'quotes'

urlpatterns = [
    # path('', views.main, name='root'),
    # path('<int:page>', views.main, name='root_paginate'),
    path('', views.home, name='home'),
    path('<int:page>', views.home, name='root_paginate'),
    path('author/<int:_id>', views.author_about, name='author_about'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag/<int:_id>/', views.find_tag, name='find_tag'),
    path('tag/<str:_id>/', views.find_tag, name='find_tag'),
    path('search_quotes/', views.search_quotes, name='search_quotes'),
    path('parse/', views.parse, name='parse')
]

HW_10/hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(template_name="users/signin.html",
                                      authentication_form=LoginForm,
                                      redirect_authenticated_user=True),
         name='login'),
    path('logout/', LogoutView.as_view(template_name="users/logout.html"),
         name='logout')
]

HW_10/hw_project/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    date_born = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=40, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

HW_10/hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, SelectMultiple, \
    ModelChoiceField, Select, ModelMultipleChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    date_born = DateField(widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=200, required=True, widget=TextInput(attrs={"class": "form-control"}))
    bio = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'date_born', 'born_location', 'bio']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                    widget=SelectMultiple(attrs={'class': 'form_control', 'size': 10}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'),
                              widget=Select(attrs={"class": "form-select"}))

    class Meta:
        model = Quote
        fields = ['author', 'tags', 'quote']


class TagForm(ModelForm):
    name = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name']

HW_10/hw_project/quotes/views.py
import os

import django
import requests
from bs4 import BeautifulSoup
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Quote, Author, Tag
from .utils import get_mongodb
from .forms import AuthorForm, QuoteForm, TagForm


# def main(request, page=1):
#     db = get_mongodb()
#     quotes = db.quotes.find()
#     per_page = 10
#     paginator = Paginator(list(quotes), per_page)
#     quotes_on_page = paginator.page(page)
#
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def home(request, page=1):
    quotes = Quote.objects.all()
    per_page = 5
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_tags = Quote.objects.values('tags__name').annotate(quote_count=Count('tags__name')).order_by('-quote_count')[
               :10]
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, 'top_tags': top_tags})


def author_about(request, _id):
    author = Author.objects.get(pk=_id)
    return render(request, 'quotes/author.html', context={'author': author})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'super_quotes/add_quote.html',
                          context={'form': QuoteForm, 'message': "Error"})
    return render(request, 'quotes/add_quote.html', context={'form': QuoteForm()})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'quotes/add_author.html',
                          context={'form': AuthorForm, 'message': "Error"})
    return render(request, 'quotes/add_author.html', context={'form': AuthorForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(to='quotes:home')
        else:
            return render(request, 'quotes/add_tag.html',
                          context={'form': TagForm, 'message': "Error"})
    return render(request, 'quotes/add_tag.html', context={'form': TagForm})


def find_tag(request, _id):
    per_page = 5
    if isinstance(_id, int):
        quotes = Quote.objects.filter(tags=_id).all()
    elif isinstance(_id, str):
        tag_id = Tag.objects.filter(name=_id).first()
        quotes = Quote.objects.filter(tags=tag_id).all()
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    top_tags = Quote.objects.values('tags__id', 'tags__name').annotate(quote_count=Count('tags__name')).order_by(
        '-quote_count')[:10]

    return render(request, 'quotes/find_tag.html',
                  context={'quotes': page_obj, 'tag_name': _id, 'top_tags': top_tags})


def search_quotes(request):
    query = request.GET.get('q')
    quotes = Quote.objects.filter(
        Q(tags__name__icontains=query) |
        Q(quote__icontains=query) |
        Q(author__fullname__icontains=query)
    ).distinct()

    return render(request, 'quotes/search_quotes.html', context={'quotes': quotes, 'query': query})


@login_required()
def parse(request):
    base_url = 'http://quotes.toscrape.com'

    def get_author_urls():
        author_links = []
        response = requests.get(base_url)
        soup = BeautifulSoup(response.text, 'html.parser')
        quotes = soup.find_all('div', class_='quote')
        for q in quotes:
            author_links.append(q.find("a", href=True).get('href'))
        return author_links

    def quote_spider():
        created_quotes = []
        response = requests.get(base_url)
        soup = BeautifulSoup(response.text, 'html.parser')
        content = soup.select('div[class=col-md-8] div[class=quote]')
        for el in content:
            quote_text = el.find('span', attrs={'class': 'text'}).text
            author_fullname = el.find('small', attrs={'class': 'author'}).text
            author, created = Author.objects.get_or_create(fullname=author_fullname)

            tags = (list(filter(bool, [t.text.strip() for t in el.find('div', class_='tags').find_all('a')])))

            new_quote, created = Quote.objects.get_or_create(quote=quote_text, author=author)
            if created:
                for tag_name in tags:
                    tag, _ = Tag.objects.get_or_create(name=tag_name)
                    new_quote.tags.add(tag)
            new_quote.save()
            created_quotes.append(new_quote)
        return created_quotes

    def author_spider():
        author_links = get_author_urls()
        created_authors = []
        for link in author_links:
            response = requests.get(base_url + link)
            soup = BeautifulSoup(response.text, 'lxml')
            content = soup.select('div[class=container] div[class=author-details]')
            for el in content:
                fullname = el.find('h3', attrs={'class': 'author-title'}).text.strip()
                date_born = el.find('span', attrs={'class': 'author-born-date'}).text.strip()
                born_location = el.find('span', attrs={'class': 'author-born-location'}).text.strip()
                bio = el.find('div', attrs={'class': 'author-description'}).text.strip()
                author, created = Author.objects.get_or_create(fullname=fullname, date_born=date_born,
                                                               born_location=born_location,
                                                               bio=bio)
                author.save()
                created_authors.append(author)
        return created_authors

    def parsing():
        return author_spider(), quote_spider()

    return render(request, 'quotes/parse.html', context={'final_parse': parsing, 'base_url': base_url})

HW_10/hw_project/quotes/templates/quotes/add_author.html
{%extends "quotes/base.html"%}

{% block content %}
<h3>Add author</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Author</label>
        {{form.fullname}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Date of birth</label>
        {{form.date_born}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Place of birth</label>
        {{form.born_location}}
    </div>
      <div class="row mb-3 col-md-6">
        <label>Biography</label>
        {{form.bio}}
    </div>


    <button type="submit" class="btn btn-primary">Add author</button>
</form>
{% endblock %}

HW_10/hw_project/quotes/templates/quotes/add_quote.html
{%extends "quotes/base.html"%}

{% block content %}
<h3>Add quote</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Quote</label>
        {{form.quote}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Chose tag</label>
        {{form.tags}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Author</label>
        {{form.author}}
    </div>
    <button type="submit" class="btn btn-primary">Add quote</button>
</form>
{% endblock %}

HW_10/hw_project/quotes/templates/quotes/add_tag.html
{%extends "quotes/base.html"%}

{% block content %}
<h3>Add tag</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Tag</label>
        {{form.name}}
    </div>
    <button type="submit" class="btn btn-primary">Add tag</button>
</form>

{% endblock %}

HW_10/hw_project/quotes/templates/quotes/author.html
{%extends "quotes/base.html"%}
{% load extract %}


{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{author.date_born}}</span> <span
                class="author-born-location">{{author.born_location}}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">{{author.bio}}</div>
</div>

{% endblock %}

HW_10/hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" style="font-size: 1.5rem">Quotes</a>

        <form class="d-flex ms-auto" role="search" method="get" action="{% url 'quotes:search_quotes' %}">
        <input class=" form-control me-2
        " type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-light" type="submit">Find</button>
        </form>

        {% if user.is_authenticated %}
        <p class="mb-0 ps-3">Welcome.</p>
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-info me-2" href="{% url 'quotes:add_quote' %}">Add quote</a>
            <a class="btn btn-info me-2" href="{% url 'quotes:add_author' %}">Add author</a>
            <a class="btn btn-info me-2" href="{% url 'quotes:add_tag' %}">Add tag</a>
            <a class="btn btn-info" href="{% url 'users:logout' %}">Log Out</a>
        </div>
        {% else %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-success me-2" href="{% url 'users:register' %}">Registration</a>
            <a class="btn btn-success" href="{% url 'users:login' %}">Log In</a>
        </div>
        {% endif %}
        {% if request.user.is_superuser %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-dark me-2" href="{% url 'quotes:parse' %}">Parse</a>
        </div>
        {% endif %}
    </div>

<div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    <a href="{% url 'users:register' %}" class="btn btn-outline-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-outline-primary">LogIn</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-outline-primary">LogOut</a>

                </p>
            </div>
        </div>


        {% block content %} {% endblock %}

    </div>
</body>
</html>

HW_10/hw_project/quotes/templates/quotes/find_tag.html
{%extends "quotes/base.html"%}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pagination">
                <li class="previous">
                    {% if quotes.has_previous %}
                    <a href="?page=1" class="btn btn-light">&laquo; First</a>
                    <a href="?page={{ quotes.previous_page_number }}" class="btn btn-light">Pevious</a>
                    {% endif %}
                    <span class="current">Page {{ quotes.number }} with {{ quotes.paginator.num_pages }}</span>
                    {% if quotes.has_next %}
                    <a href="?page={{ quotes.next_page_number }}" class="btn btn-light">Next</a>
                    <a href="?page={{ quotes.paginator.num_pages }}" class="btn btn-light">Last &raquo;</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags">
            <a class="btn btn-info" href="{% url 'super_quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

HW_10/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
    </div>

    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span>
                </a>
            </li>
        </ul>
    </nav>
    </div>

</div>

{% endblock %}

HW_10/hw_project/quotes/templates/quotes/parse.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="row">
    <h4>Parse {{ base_url }} already finished</h4>
    <div class="col-md-8">
        {% for author in final_parse.author_spider %}
        {% if author_created %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">"{{ author }}" has been successfuly added!</span>
            {% endif %}
            {% endfor %}
        </div>
        {% for quote in final_parse.quote_spider %}
        {% if quote_created %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">"{{ quote }}" has been successfuly added!</span>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

HW_10/hw_project/quotes/templates/quotes/search_quotes.html
{%extends "quotes/base.html"%}
{% load extract %}

{% block content %}
<div class="row">
    <h4>Search by word: {{query}}</h4>
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags">
            <a class="btn btn-info" href="{% url 'quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}